import * as fs from 'fs';

let content = fs.readFileSync('server/routes.ts', 'utf-8');

content = content.replace(`import Database from './replit-db-mock';\nimport { z } from "zod";\n\nconst db = new Database();\n`, `import { z } from "zod";\n`);

content = content.replace(`async function dbGet<T>(key: string): Promise<T | null> {\n  const result = await db.get(key) as { ok: boolean; value?: T };\n  if (!result.ok) return null;\n  return result.value ?? null;\n}\n\nasync function dbSet(key: string, value: any): Promise<void> {\n  await db.set(key, value);\n}\n\nexport async function registerRoutes(app: Express): Promise<Server> {`, `export async function registerRoutes(app: Express): Promise<Server> {`);

content = content.replace(`      const normalizedEmail = email.toLowerCase().trim();\n      const key = \`user:\${normalizedEmail}\`;\n      let user = await dbGet<any>(key);\n      \n      if (!user) {\n        // Create new record for first-time login\n        user = {\n          ticketType: null,\n          ticketLocked: false,\n          selectedSeat: null,\n          updatedAt: new Date().toISOString()\n        };\n        await dbSet(key, user);\n      }`, `      const normalizedEmail = email.toLowerCase().trim();\n      let user = await storage.getUser(normalizedEmail);\n      \n      if (!user) {\n        user = await storage.createUser(normalizedEmail);\n      }`);

content = content.replace(`      const email = (req.query.email as string)?.toLowerCase().trim();\n      if (!email) return res.status(400).json({ error: 'Email is required' });\n      \n      const user = await dbGet<any>(\`user:\${email}\`);\n      if (!user) return res.status(404).json({ error: 'User not found' });`, `      const email = (req.query.email as string)?.toLowerCase().trim();\n      if (!email) return res.status(400).json({ error: 'Email is required' });\n      \n      const user = await storage.getUser(email);\n      if (!user) return res.status(404).json({ error: 'User not found' });`);

content = content.replace(`      const key = \`user:\${email}\`;\n      const existing = await dbGet<any>(key) || {};\n      // Only set if not already locked\n      if (existing.ticketLocked) {\n        return res.json({ ticketType: existing.ticketType, ticketLocked: true });\n      }\n      const now = new Date().toISOString();\n      await dbSet(key, { ...existing, ticketType, ticketLocked: true, updatedAt: now });\n      res.json({ ticketType, ticketLocked: true });`, `      const existing = await storage.getUser(email);\n      if (!existing) {\n        return res.status(404).json({ error: 'User not found' });\n      }\n      // Only set if not already locked\n      if (existing.ticketLocked) {\n        return res.json({ ticketType: existing.ticketType, ticketLocked: true });\n      }\n      const updated = await storage.updateUser(email, { ticketType, ticketLocked: true });\n      res.json({ ticketType: updated.ticketType, ticketLocked: true });`);

content = content.replace(`      const userRecord = await dbGet<any>(\`user:\${booking.bookedByEmail}\`);\n      if (userRecord?.selectedSeat) {\n        const claimedSeat = await storage.getSeat(userRecord.selectedSeat.seatId);\n        const isStillBooked = claimedSeat?.status === 'booked' && claimedSeat?.bookedByEmail === booking.bookedByEmail;\n        if (isStillBooked) {\n          return res.status(409).json({ error: 'You already have a booked seat. Please choose another seat.' });\n        }\n        // Stale record - seat no longer booked by this email. Clear it so the user can book.\n        await dbSet(\`user:\${booking.bookedByEmail}\`, { ...userRecord, selectedSeat: null, updatedAt: new Date().toISOString() });\n      }`, `      const userRecord = await storage.getUser(booking.bookedByEmail);\n      if (userRecord?.selectedSeat) {\n        const claimedSeat = await storage.getSeat(userRecord.selectedSeat.seatId);\n        const isStillBooked = claimedSeat?.status === 'booked' && claimedSeat?.bookedByEmail === booking.bookedByEmail;\n        if (isStillBooked) {\n          return res.status(409).json({ error: 'You already have a booked seat. Please choose another seat.' });\n        }\n        // Stale record - seat no longer booked by this email. Clear it so the user can book.\n        await storage.updateUser(booking.bookedByEmail, { selectedSeat: null });\n      }`);

content = content.replace(`      // Persist booking on the user record so finality is enforced going forward\n      const userKey = \`user:\${booking.bookedByEmail}\`;\n      const existingUser = (await dbGet<any>(userKey)) || {};\n      await dbSet(userKey, {\n        ...existingUser,\n        fullName: booking.bookedBy,\n        selectedSeat: { floor: seat.floor, row: seat.row, pos: seat.position, seatId: seat.id },\n        updatedAt: new Date().toISOString(),\n      });`, `      // Persist booking on the user record so finality is enforced going forward\n      const existingUser = await storage.getUser(booking.bookedByEmail);\n      if (existingUser) {\n        await storage.updateUser(booking.bookedByEmail, {\n          fullName: booking.bookedBy,\n          selectedSeat: { floor: seat.floor, row: seat.row, pos: seat.position, seatId: seat.id },\n        });\n      }`);

content = content.replace(`      const prevEmail = previousSeat?.bookedByEmail;\n      if (prevEmail) {\n        const prevUser = await dbGet<any>(\`user:\${prevEmail}\`);\n        if (prevUser?.selectedSeat?.seatId === req.params.id) {\n          await dbSet(\`user:\${prevEmail}\`, { ...prevUser, selectedSeat: null, updatedAt: new Date().toISOString() });\n        }\n      }`, `      const prevEmail = previousSeat?.bookedByEmail;\n      if (prevEmail) {\n        const prevUser = await storage.getUser(prevEmail);\n        if (prevUser?.selectedSeat?.seatId === req.params.id) {\n          await storage.updateUser(prevEmail, { selectedSeat: null });\n        }\n      }`);

content = content.replace(`      const prevEmail = previousSeat?.bookedByEmail;\n      const newEmail = seat.bookedByEmail;\n      if (prevEmail && prevEmail !== newEmail) {\n        const prevUser = await dbGet<any>(\`user:\${prevEmail}\`);\n        if (prevUser?.selectedSeat?.seatId === req.params.id) {\n          await dbSet(\`user:\${prevEmail}\`, { ...prevUser, selectedSeat: null, updatedAt: new Date().toISOString() });\n        }\n      }\n      if (newEmail && seat.status === 'booked') {\n        const newUser = await dbGet<any>(\`user:\${newEmail}\`) || {};\n        await dbSet(\`user:\${newEmail}\`, {\n          ...newUser,\n          fullName: seat.bookedBy,\n          selectedSeat: { floor: seat.floor, row: seat.row, pos: seat.position, seatId: seat.id },\n          updatedAt: new Date().toISOString(),\n        });\n      }`, `      const prevEmail = previousSeat?.bookedByEmail;\n      const newEmail = seat.bookedByEmail;\n      if (prevEmail && prevEmail !== newEmail) {\n        const prevUser = await storage.getUser(prevEmail);\n        if (prevUser?.selectedSeat?.seatId === req.params.id) {\n          await storage.updateUser(prevEmail, { selectedSeat: null });\n        }\n      }\n      if (newEmail && seat.status === 'booked') {\n        let newUser = await storage.getUser(newEmail);\n        if (!newUser) newUser = await storage.createUser(newEmail);\n        \n        await storage.updateUser(newEmail, {\n          fullName: seat.bookedBy,\n          selectedSeat: { floor: seat.floor, row: seat.row, pos: seat.position, seatId: seat.id },\n        });\n      }`);

content = content.replace(`      // Clear selectedSeat on every user record so they can book again\n      try {\n        const listResult = await db.list('user:') as { ok: boolean; value?: string[] };\n        const keys = listResult.ok && Array.isArray(listResult.value) ? listResult.value : [];\n        await Promise.all(keys.map(async (k) => {\n          const user = await dbGet<any>(k);\n          if (user?.selectedSeat) {\n            await dbSet(k, { ...user, selectedSeat: null, updatedAt: new Date().toISOString() });\n          }\n        }));\n      } catch (e) {\n        console.warn('Failed to clear user selectedSeat on reset:', e);\n      }`, `      // Clear selectedSeat on every user record so they can book again\n      try {\n        const allUsers = await storage.getAllUsers();\n        await Promise.all(allUsers.map(async (user) => {\n          if (user.selectedSeat) {\n            await storage.updateUser(user.email, { selectedSeat: null });\n          }\n        }));\n      } catch (e) {\n        console.warn('Failed to clear user selectedSeat on reset:', e);\n      }`);

content = content.replace(`      const userTicketTypes = await Promise.all(\n        bookedSeats.map(async seat => {\n          if (!seat.bookedByEmail) return '';\n          const userRecord = await dbGet<any>(\`user:\${seat.bookedByEmail.toLowerCase().trim()}\`);\n          return userRecord?.ticketType ?? '';\n        })\n      );`, `      const userTicketTypes = await Promise.all(\n        bookedSeats.map(async seat => {\n          if (!seat.bookedByEmail) return '';\n          const userRecord = await storage.getUser(seat.bookedByEmail);\n          return userRecord?.ticketType ?? '';\n        })\n      );`);

fs.writeFileSync('server/routes.ts', content);
console.log('Done replacement');
